name: srcreative
favicon: null
layout_spectrum: 0.99913
typography_spectrum: 0.4302
title: suzanne rushton creative
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fb0760'
    - '#634147'
    - '#7c7e8d'
    - '#d9c9a5'
  brandStrength: 0.7209567117970437
  lightness: 0.8695786404423416
  saturation: 0.5070546129718423
  rhythmicContrast: 0.3428102917969227
purpose: []
